#!/bin/bash

# Değişkenler
version="2"
author="ByCh4n"

# Klasik renk değişkenlerimiz
    cyan='\e[0;36m'
    lightcyan='\e[96m'
    lightgreen='\e[1;32m'
    white='\e[1;37m'
    red='\e[1;31m'
    yellow='\e[1;33m'
    blue='\e[1;34m'
    green='\e[0;32m'
    reset='\e[0m'

banner() {
	echo -e "
ICAgICAgICAgICAgICwtLS0tLS0tLS0tLS0tLS0tLCAgICAgICAgICAgICAgLC0tLS0tLS0tLSwK
ICAgICAgICAsLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0sICAgICAgICAgICwiICAgICAgICAsInwK
ICAgICAgLCIgICAgICAgICAgICAgICAgICAgICAgLCJ8ICAgICAgICAsIiAgICAgICAgLCIgIHwK
ICAgICArLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0rICB8ICAgICAgLCIgICAgICAgICwiICAgIHwg
R2l0SHViICAgIDogQnlDaDRuCiAgICAgfCAgLi0tLS0tLS0tLS0tLS0tLS0tLiAgfCAgfCAgICAg
Ky0tLS0tLS0tLSsgICAgICB8IEluc3RhZ3JhbSA6IGh1c2V5aW5hbHRucwogICAgIHwgIHwgICAg
QXV0b21hdGljICAgIHwgIHwgIHwgICAgIHwgLT09LS0tLSd8ICAgICAgfCBEaXNjb3JkICAgOiBk
aXNjb3JkLmdnL201QjRjNXJuYlIKICAgICB8ICB8ICAgICBQcm9ncmFtICAgICB8ICB8ICB8ICAg
ICB8ICAgICAgICAgfCAgICAgIHwKICAgICB8ICB8ICAgIEluc3RhbGxlciEgICB8ICB8ICB8Ly0t
LS18YC0tLT0gICAgfCAgICAgIHwKICAgICB8ICB8ICBDOlw+XyAgICAgICAgICB8ICB8ICB8ICAg
LC98PT09PSBvb28gfCAgICAgIDsKICAgICB8ICB8ICAgICAgICAgICAgICAgICB8ICB8ICB8ICAv
LyB8KCgoKCBbMzNdfCAgICAsIgogICAgIHwgIGAtLS0tLS0tLS0tLS0tLS0tLScgIHwsIiAuOyd8
IHwoKCgoICAgICB8ICAsIgogICAgICstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSsgIDs7ICB8IHwg
ICAgICAgICB8LCIgICAgIAogICAgICAgIC9fKV9fX19fX19fX19fX19fKF8vICAvLycgICB8ICst
LS0tLS0tLS0rCiAgIF9fX19fX19fX19fX19fX19fX19fX19fX19fXy9fX18gIGAsCiAgLyAgb29v
b29vb29vb29vb29vbyAgLm8uICBvb29vIC8sICAgXCwiLS0tLS0tLS0tLS0KIC8gPT1vb29vb29v
b29vb29vb289PS5vLiAgb29vPSAvLyAgICxgXC0teylCICAgICAsIgovXz09X189PT09PT09PT09
X189PV9vb29fX29vbz1fLycgICAvX19fX19fX19fX18sIgpgLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0nCg==
" | base64 -d && echo -e ""
}

checknet() {
    ping -q -w1 -c1 google.com &>/dev/null && netcheck="online" || netcheck="offline"
    case ${1} in
        print|PRINT|-p)
            echo "${netcheck}"
        ;;
    esac
}

checkos() {
	if [[ $(uname -v) == *kali* ]] ; then
		os="kali"
	elif [ -e /etc/arch-release ] ; then
		os="arch"
	elif [ -e /etc/apt/sources.list ] ; then
		os="debian"
	else
		os="unknow"
	fi
}

# THIS FUNCTION IS ABSOLETLY BROKEN I WILL FIX IT AFTER
updatekalirepos() {
	[ $(command -v git) ] || { pkexec apt install git ; }
	[ -d kalisources ] || git clone https://github.com/lastpingu/kalisources
	[ $UID = 0 ] || { echo "run it as root!" ; exit 1 ; }
	cd kalisources
	bash kalisources
}

main() {
while :
do
	checkos
	checknet -p
	[[ $netcehck = "offline" ]] && { echo -e "${red}Please check your internet connection${reset}" ; exit 1 ; }
	echo -ne "${yellow}$(banner)${reset}\n\n${lightgreen} 	[1]${reset} ► ${white}Otomatik Yükleyiciyi Başlat ( Launch Auto Installer )${reset} ◄
	${lightgreen}$([ $os != kali ] && echo -e "${red}")[2]${reset}$([ $os != kali ] && echo -e "${red}") ► ${white}$([ $os != kali ] && echo -e "${red}")Kali Linux Depo Güncelle ( Kali Linux Repository Update )${reset}$([ $os != kali ] && echo -e "${red}") ◄
	${lightgreen}[x]${reset} ► ${white}Çıkış ( Exit )${reset} ◄\n\n	┌─[${blue}${author}${reset}@${blue}${0}${reset}]─[~/${lightcyan}Main${reset}]\n	└──╼ $ ${reset}"
	read option
	
	case "$option" in
			1)
				echo -e "${cyan} ► Otomatik Yükleyici Başlatıldı ( Auto Installer Started ) ❤ ツ ◄${reset}" 
				echo -e "${cyan} ► Gerekli Programlar Yükleniyor Lütfen Sabırla Bekleyiniz... ( Required Programs Loading Please Wait Patiently... ) ❤ ツ ◄${reset}"
								
				case $os in
					debian|kali)
						[ $UID != 0 ] && { echo -e "${red}Run as root! sudo bash $0" ; exit 1 ; }
						apt update
						apt install -y python3 python3-pip git php nmap tor default-jdk curl openssh openssl wget unzip vi vim nano
						echo -e "\n${green}Now This Step Can Be It May Take Time..${reset}"
						apt upgrade -y && apt autoremove -y						
					;;
					arch)
						[ $UID != 0 ] && { echo -e "${red}Run as root! sudo bash $0" ; exit 1 ; }
						pacman -Syy
						pacman -Sy --noconfirm python3 python3-pip git php nmap tor default-jdk curl openssh openssl wget unzip vi vim nano
						echo -e "\n${green}Now This Step Can Be It May Take Time..${reset}"
						pacman -Syyu --noconfirm
					;;
					unknow)
						echo "Unknow distro"
					;;
				esac
				pip3 install -y setuptools tor curl mechanize stem php colorama clint
				echo -e "${blue} ► Gerekli Program aracı görevini tamamladı lütfen bir hata olmadığından emin olunuz eğer hata var ise bizimle iletişime geçiniz ✓ ◄${reset}"
			;;
			2)
				[ $os != "kali" ] && { echo -e "\nBu seçeneği kali dağıtımı dışında kullanamazsınız." ; exit 1 ; }
				updatekalirepos
			;;
			[eE][xX][iI][tT]|[xX])
				echo -e "${blue} ByChan Programını Tercih Ettiğin İçin Teşekkürler. ${red}❤${blue} ツ\n${green} Thank you for choosing the ByChan Program. ${red}❤${blue} ツ${reset}\n"
				exit 0
			;;
			[cC][lL][eE][aA][rR]|[cC][lL][sS]|[cC])
				clear
			;;
			*)
				echo -e "\n${red}	Bilinmeyen girdi?? (Unknow option)${reset}\n"
			;;
			esac
    done
}

main
