#!/usr/bin/env bash

#Colors
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
echo ""
sleep 2

clear
function main_menu()
{
    while :
    do
clear
cat banner/banner.txt
echo -e $green " »»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»"
echo -e $green " ByChan Gerekli Program Yükleyici Ⓒ"
echo -e $green " ByChan Required Program Installer Ⓒ"
echo -e $green " «««««««««««««««««««««««««««««««««««"
echo
echo -e $green " [1] ► Otomatik Yükleyiciyi Başlat ( Launch Auto Installer ) ◄"
echo -e $green " [2] ► Kali Linux Depo Güncelle ( Kali Linux Repository Update ) ◄"
echo -e $green " [x] ► Çıkış ( Exit ) ◄"
echo
read -p "ByChan > " option
echo

case "$option" in
        1)
            echo -e $cyan " ► Otomatik Yükleyici Başlatıldı ( Auto Installer Started ) ◄"
			sleep 4
			echo -e $cyan " ► Kanala Abone Olup Like Atmayı Unutma ❤ ツ ◄"
			echo -e $cyan " ► Do not forget to subscribe and like the channel ❤ ツ ◄" 
            echo -e $cyan " ► Gerekli Programlar Yükleniyor Lütfen Sabırla Bekleyiniz... ◄"
			echo -e $cyan " ► Required Programs Loading Please Wait Patiently ... ◄"
            {
			git pull &> /dev/null
			echo -e $red "OK"
			pkg update -y &> /dev/null
			echo -e $red "OK"
			pkg update -y &> /dev/null
			echo -e $red "OK"
            pkg upgrade -y &> /dev/null
			echo -e $red "OK"
            pkg install python -y &> /dev/null
			echo -e $red "OK"
            pkg install python2 -y &> /dev/null
			echo -e $red "OK"
            pkg install python3 -y &> /dev/null
			echo -e $red "OK"
            pkg install git -y &> /dev/null
			echo -e $red "OK"
            pkg install nano -y &> /dev/null
			echo -e $red "OK"
            pip install openssl -y &> /dev/null
			echo -e $red "OK"
            pkg install openssl -y &> /dev/null
			echo -e $red "OK"
			pkg install openssh -y &> /dev/null
			echo -e $red "OK"
			termux-setup-storage -y &> /dev/null
			echo -e $red "OK"
			pip install requests -y &> /dev/null
			echo -e $red "OK"
            pkg install tor -y &> /dev/null
			echo -e $red "OK"
            pkg install curl -y &> /dev/null
			echo -e $red "OK"
            pip install curl -y &> /dev/null
			echo -e $red "OK"
            pip install tor -y &> /dev/null
			echo -e $red "OK"
            pip2 install mechanize -y &> /dev/null
			echo -e $red "OK"
            apt update -y &> /dev/null
			echo -e $red "OK"
            apt upgrade -y &> /dev/null
			echo -e $red "OK"
			apt autoremove -y &> /dev/null
			echo -e $red "OK"
			apt full-upgrade -y &> /dev/null
			echo -e $red "OK"
            apt-update && apt upgrade -y &> /dev/null
			echo -e $red "OK"
            pkg install git python php curl openssh grep -y &> /dev/null
			echo -e $red "OK"
            pip install stem -y &> /dev/null
			echo -e $red "OK"
			pkg -y install git -y &> /dev/null
			echo -e $red "OK"
			pkg -y install python -y &> /dev/null
			echo -e $red "OK"
			sudo apt-get update -y &> /dev/null
			echo -e $red "OK"
			sudo apt-get -y install git &> /dev/null
			echo -e $red "OK"
			sudo apt-get -y install python3 &> /dev/null
			echo -e $red "OK"
			sudo apt-get -y install python3-pip &> /dev/null
			echo -e $red "OK"
            apt update -y &> /dev/null
			echo -e $red "OK"
            apt upgrade -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install python -y &> /dev/null
			echo -e $red "OK"
            sudo apt get install python2 -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install python3 -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install python-pip -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install python2-pip -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install python3-pip -y &> /dev/null
			echo -e $red "OK"
            sudo pip install mechanize -y &> /dev/null
			echo -e $red "OK"
            sudo pip2 install mechanize -y &> /dev/null
			echo -e $red "OK"
            sudo pip install php -y &> /dev/null
			echo -e $red "OK"
            sudo pip install tor -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install tor -y &> /dev/null
			echo -e $red "OK"
            sudo pip3 install requests -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install nmap -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install torghost -y &> /dev/null
			echo -e $red "OK"
            sudo pip3 install clint -y &> /dev/null
			echo -e $red "OK"
            sudo pip3 install coloramas -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install default-jdk -y &> /dev/null
			echo -e $red "OK"
            sudo apt-get install php -y &> /dev/null
			echo -e $red "OK"
			apk update &> /dev/null
			echo -e $red "OK"
			apk add git &> /dev/null
			echo -e $red "OK"
			apk add python3 &> /dev/null
			echo -e $red "OK"
			apk add py3-pip &> /dev/null
			echo -e $red "OK"
			pacman -Sy &> /dev/null
			echo -e $red "OK"
			pacman -S --noconfirm git &> /dev/null
			echo -e $red "OK"
			pacman -S --noconfirm python3 &> /dev/null
			echo -e $red "OK"
			pacman -S --noconfirm python3-pip &> /dev/null
			echo -e $red "OK"
			zypper refresh &> /dev/null
			echo -e $red "OK"
			zypper install -y git &> /dev/null
			echo -e $red "OK"
			zypper install -y python3 &> /dev/null
			echo -e $red "OK"
			zypper install -y python3-pip &> /dev/null
			echo -e $red "OK"
			yum -y install git &> /dev/null
			echo -e $red "OK"
			yum -y install python3 &> /dev/null
			echo -e $red "OK"
			yum -y install python3-pip &> /dev/null
			echo -e $red "OK"
			dnf -y install git &> /dev/null
			echo -e $red "OK"
			dnf -y install python3 &> /dev/null
			echo -e $red "OK"
			dnf -y install python3-pip &> /dev/null
			echo -e $red "OK"
			eopkg update-repo &> /dev/null
			echo -e $red "OK"
			eopkg -y install git &> /dev/null
			echo -e $red "OK"
			eopkg -y install python3 &> /dev/null
			echo -e $red "OK"
			eopkg -y install pip &> /dev/null
			echo -e $red "OK"
			xbps-install -S &> /dev/null
			echo -e $red "OK"
			xbps-install -y git &> /dev/null
			echo -e $red "OK"
			xbps-install -y python3 &> /dev/null
			echo -e $red "OK"
			xbps-install -y python3-pip &> /dev/null
			echo -e $red "OK"
			sudo python3 -m pip install setuptools -y &> /dev/null
			echo -e $red "OK"
			sleep 2
            }
			echo -e $blue " ► Gerekli Programlar Yüklendi ✓ ( Required Programs Installed ) ◄"
			sleep 3
            ;;
		2)
			echo -e $blue " ► Kali Linux Depo Güncelleniyor... ( Updating Kali Linux Repository... ) ◄"
			sleep 2
			{
			echo -e "deb http://http.kali.org/kali kali-rolling main non-free contrib \n deb http://http.kali.org/kali kali-last-snapshot main non-free contrib \n deb http://http.kali.org/kali kali-experimental main non-free contrib \n deb-src http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
			} &> /dev/null
			echo -e $blue " ► Kali Linux Deposu Güncellendi Otomatik Yükleyiciyi Başlatabilirsiniz... ◄"
			echo -e $blue " ► Kali Linux Repository Updated You Can Start the Auto Installer ... ◄     "
			sleep 5
			;;
        x)
            echo -e $blue -" ByChan Programını Tercih Ettiğin İçin Teşekkürler. ❤ ツ"
			echo -e $blue -" Thank you for choosing the ByChan Program. ❤ ツ"
            echo
            exit 0
        esac
    done
}
main_menu
